// <auto-generated />
using System;
using Marketplace.Modules.Location.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Marketplace.Modules.Location.Persistence.Migrations
{
    [DbContext(typeof(LocationDbContext))]
    [Migration("20261009093034_AddPlacesAndLocations")]
    partial class AddPlacesAndLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("location")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Marketplace.Modules.Location.Domain.ItemLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("area_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Point>("Geo")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("geo");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Point>("PublicGeo")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("public_geo");

                    b.HasKey("Id")
                        .HasName("pk_item_location");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_item_location_owner_id");

                    b.ToTable("item_location", "location");
                });

            modelBuilder.Entity("Marketplace.Modules.Location.Domain.Place", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("kind");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_place");

                    b.ToTable("place", "location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Chicago",
                            Kind = "city",
                            Latitude = 41.878100000000003,
                            Longitude = -87.629800000000003,
                            Name = "Chicago, IL"
                        },
                        new
                        {
                            Id = 2,
                            City = "New York",
                            Kind = "city",
                            Latitude = 40.678199999999997,
                            Longitude = -73.944199999999995,
                            Name = "Brooklyn, NY"
                        },
                        new
                        {
                            Id = 3,
                            City = "Dallas",
                            Kind = "city",
                            Latitude = 32.776699999999998,
                            Longitude = -96.796999999999997,
                            Name = "Dallas, TX"
                        },
                        new
                        {
                            Id = 4,
                            City = "Seattle",
                            Kind = "city",
                            Latitude = 47.606200000000001,
                            Longitude = -122.3321,
                            Name = "Seattle, WA"
                        },
                        new
                        {
                            Id = 5,
                            City = "Portland",
                            Kind = "city",
                            Latitude = 45.5152,
                            Longitude = -122.6784,
                            Name = "Portland, OR"
                        },
                        new
                        {
                            Id = 6,
                            City = "San Diego",
                            Kind = "city",
                            Latitude = 32.715699999999998,
                            Longitude = -117.1611,
                            Name = "San Diego, CA"
                        },
                        new
                        {
                            Id = 101,
                            City = "Chicago",
                            Kind = "area",
                            Latitude = 41.908799999999999,
                            Longitude = -87.677599999999998,
                            Name = "Wicker Park, Chicago"
                        },
                        new
                        {
                            Id = 102,
                            City = "Chicago",
                            Kind = "area",
                            Latitude = 41.884999999999998,
                            Longitude = -87.784499999999994,
                            Name = "Oak Park"
                        },
                        new
                        {
                            Id = 103,
                            City = "Chicago",
                            Kind = "area",
                            Latitude = 42.045099999999998,
                            Longitude = -87.687700000000007,
                            Name = "Evanston"
                        },
                        new
                        {
                            Id = 104,
                            City = "Chicago",
                            Kind = "area",
                            Latitude = 41.750799999999998,
                            Longitude = -88.153499999999994,
                            Name = "Naperville"
                        },
                        new
                        {
                            Id = 105,
                            City = "Chicago",
                            Kind = "area",
                            Latitude = 41.8827,
                            Longitude = -87.647999999999996,
                            Name = "West Loop, Chicago"
                        },
                        new
                        {
                            Id = 106,
                            City = "Chicago",
                            Kind = "area",
                            Latitude = 41.7943,
                            Longitude = -87.590699999999998,
                            Name = "Hyde Park, Chicago"
                        },
                        new
                        {
                            Id = 107,
                            City = "Chicago",
                            Kind = "area",
                            Latitude = 41.921399999999998,
                            Longitude = -87.651300000000006,
                            Name = "Lincoln Park, Chicago"
                        },
                        new
                        {
                            Id = 108,
                            City = "Chicago",
                            Kind = "area",
                            Latitude = 41.878599999999999,
                            Longitude = -87.625100000000003,
                            Name = "The Loop, Chicago"
                        });
                });

            modelBuilder.Entity("Marketplace.Modules.Location.Domain.UserLocation", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("area_name");

                    b.Property<Point>("PublicGeo")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("public_geo");

                    b.Property<int?>("RadiusKm")
                        .HasColumnType("integer")
                        .HasColumnName("radius_km");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_user_location");

                    b.ToTable("user_location", "location");
                });

            modelBuilder.Entity("Marketplace.SharedKernel.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Handler")
                        .HasName("pk_inbox_message");

                    b.ToTable("inbox_message", "location");
                });

            modelBuilder.Entity("Marketplace.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_message_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_message", "location");
                });
#pragma warning restore 612, 618
        }
    }
}
